### ISSUE TITLE
does this support none integer framerates

### ISSUE THREAD

**Issue by benroeder** [bbc/pydvbcss#10]
24000/1001 fps 23.98 23.976 etc
30000/1001 fps 29.97 etc

**Comment by matt-hammond-001** [comment]
The data model behind the protocols certainly does (see [DVB spec](https://www.dvb.org/resources/public/standards/a167-2_dvb-css_part_2_content-ID-and-media-sync_June2016.pdf) clause 5.3.2 and 5.4 and 5.5.9.5). For example, if a TV advertises timelines it has available in a CII message, then the tick-per-second tick rate is specified as `unitsPerSecond` (numerator) divided by `unitsPerTick` (denominator).

The implementation in this library does not maintain it as a numerator/denominator, and instead stores tick rates as a simple python number. But non-integer values are supported.

**Comment by matt-hammond-001** [comment]
It looks like this question has not resulted in any bugs or feature requests. Am therefore closing the issue.
