### ISSUE TITLE
ImportError: No module named wsgiserver2

### ISSUE THREAD

**Issue by ramdhany** [bbc/pydvbcss#13]
Attempting to run 'examples/WallClockServer.py' fails with this error:
ImportError: No module named wsgiserver2

**Comment by matt-hammond-001** [comment]
This appears to be related to this issue in ws4py which has arisen due to a change in cherrypy: https://github.com/Lawouach/WebSocket-for-Python/issues/205

I think it might also affect pydvbcss directly as it does climb into cherrypy for some things to do with the HTTP/wsgi server.

**Comment by matt-hammond-001** [comment]
Can fix our code to import the HttpConnection class from cheroot, but also need ws4py to have this. Unfortunately Lawouach/WebSocket-for-Python#205 has not yet made it to a PyPI release.

**Comment by matt-hammond-001** [comment]
Ok, temporary fix put into master: #f8ec3f6

Changed README and setup.py for installation process to install a specific earlier version of cherrypy and ws4py libraries.

Will push out as a new 0.4.1 release today.

Changes will need to be reverted once ws4py is updated, and changes made to this code to match (should do that work in a branch).

**Comment by matt-hammond-001** [comment]
Lawouach/WebSocket-for-Python#209 has confirmed new 0.3.6 release of ws4py due soon. Will revert master once that is released.

**Comment by matt-hammond-001** [comment]
New release confirmed. Reverting and fixing master.
