### ISSUE TITLE
Python setup.py run and test doesnt work(Python 3.7)

### ISSUE THREAD

**Issue by omertairi04** [bbc/pydvbcss#19]
Python setup.py run and test doesnt work , whenever i try to run it gives me that i need to be a superuser of this repo, and whenever i run other commands to check the examples i get a lot of errors and the code doesn't work, it might be because i am a beginner in this field but would love some help❤️

**Comment by matt-hammond-001** [comment]
This is fairly common depending on what platform you are using. 

For a beginner, I'd recommend running it within a [python virtual environment](https://www.pythonforbeginners.com/basics/how-to-use-python-virtualenv) where the packages you install are just within that project you are working on and don't affect your whole system.
